### PR TITLE
Pull request to add folder 'preprints' 

### PR DESCRIPTION
**Pull request by bmkramer**
Hi Martin, 

Hope this works! As noted, I removed all other folders from the forked repo and it now contains only my new folder 'preprints' (+ adapted Readme + license).

kind regards, Bianca

### CODE REVIEW

**Review by mfenner — CHANGES_REQUESTED** [review]
This will delete all other content. I will merge this manually.

**Comment by mfenner** [comment]
@bmkramer do you have `index.Rmd`, used to generate `index.md`?

**Comment by bmkramer** [comment]
@mfenner *revealing more ignorance* No, I edited manually. BUT happy to look into it and learn more about the proper way of doing it. Will do that later today or tomorrow and let you know.

**Comment by mfenner** [comment]
@bmkramer I will close this pull request and not merge. I added you `index.md` and figure manually.

**Pull request closed without merging**
